import * as Commerce from "commerce-kit";

export const products: Commerce.MappedProduct[] = [
	{
		id: "1",
		name: "Espresso",
		metadata: {
			slug: "espresso",
			stock: 10,
		},
		images: [
			"https://files.stripe.com/links/MDB8YWNjdF8xT3BaeG5GSmNWbVh6bURsfGZsX3Rlc3RfaDVvWXowdU9ZbWlobUIyaHpNc1hCeDM200NBzvUjqP",
		],
		default_price: {
			id: "price_1",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: Date.now() / 1000,
			currency: "usd",
			custom_unit_amount: null,
			livemode: false,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "1",
			recurring: null,
			tax_behavior: "unspecified",
			tiers_mode: null,
			transform_quantity: null,
			type: "one_time",
			unit_amount: 250,
			unit_amount_decimal: "250",
		},
		marketing_features: [],
		object: "product",
		active: true,
		created: Date.now() / 1000,
		description: "Rich and aromatic espresso.",
		livemode: false,
		package_dimensions: null,
		shippable: true,
		statement_descriptor: null,
		tax_code: null,
		type: "good",
		unit_label: null,
		updated: Date.now() / 1000,
		url: null,
	},
	{
		id: "2",
		name: "Americano",
		metadata: {
			slug: "americano",
			stock: 10,
		},
		images: [
			"https://files.stripe.com/links/MDB8YWNjdF8xT3BaeG5GSmNWbVh6bURsfGZsX3Rlc3RfaDVvWXowdU9ZbWlobUIyaHpNc1hCeDM200NBzvUjqP",
		],
		default_price: {
			id: "price_2",
			object: "price",
			active: true,
			billing_scheme: "per_unit",
			created: Date.now() / 1000,
			currency: "usd",
			custom_unit_amount: null,
			livemode: false,
			lookup_key: null,
			metadata: {},
			nickname: null,
			product: "2",
			recurring: null,
			tax_behavior: "unspecified",
			tiers_mode: null,
			transform_quantity: null,
			type: "one_time",
			unit_amount: 300,
			unit_amount_decimal: "300",
		},
		marketing_features: [],
		object: "product",
		active: true,
		created: Date.now() / 1000,
		description: "Espresso with hot water.",
		livemode: false,
		package_dimensions: null,
		shippable: true,
		statement_descriptor: null,
		tax_code: null,
		type: "good",
		unit_label: null,
		updated: Date.now() / 1000,
		url: null,
	},
];